pull_request_rules:
  - name: Automatic merge on Pull Request
    conditions:
      - author=Hugovidafe
    actions:
      merge:
        method: merge
  - name: Merge non-breaking dependencies automatically
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - title~=from (?P<major>\d+).\d+.\d+ to (?P=major).\d+.\d+
    actions:
      backport:
        branches:
          - dev
      merge:
        method: merge
      delete_head_branch:
  - name: Notify breaking dependencies automatically
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - title~=from (?P<major>\d+).\d+.\d+ to (?!(?P=major).\d+.\d+)
    actions:
      comment:
        message: |
          This PR features a major change and requires further approval.
      backport:
        branches:
          - dev
      request_reviews:
        users:
          - Hugovidafe
      delete_head_branch: